## NUSCENES DATASET ############################################################
VERSION: "v1.0-mini"            # nuscenes dataset version
SPLIT: "mini_val"               # nuscenes dataset split
VERBOSE: True                   # enable verbose mode

## DATALOADER ##################################################################
COORDINATES: "vehicle"    # coordinate system to return all data in
                          # "vehicle" or "global"
SAMPLE_MODE: "one_cam"    # sample structure
                          # "one_cam": sample contains one image from one camera
                          # "all_cam" sample contains images from all cameras
FILTER_PC: True           # in the "one_cam" mode, include only points inside the image
FILTER_ANNS: True         # in the "one_cam" mode, include only annotations inside the image

LIDAR_SWEEPS: 1           # number of LIDAR sweeps
RADAR_SWEEPS: 1           # number of Radar sweeps
BOX_VELOCITY: False       # calculate velocity for each annotation
MAX_BOX_DIST: 0           # Maximum box distance in m to include in annotations 
                          # (0 for no limit on distance)

## sensors to include in the dataloader. All sensors not in this list are ignored.
SENSORS: [
  "CAM_FRONT_LEFT",
  "CAM_FRONT_RIGHT",
  "CAM_FRONT",
  "CAM_BACK_LEFT",
  "CAM_BACK_RIGHT",
  "CAM_BACK",
  "RADAR_FRONT_LEFT",
  "RADAR_FRONT_RIGHT",
  "RADAR_FRONT",
  "RADAR_BACK_LEFT",
  "RADAR_BACK_RIGHT",
  "LIDAR_TOP",
]

## classes to include in dataloader and their name mapping. 
## All annotations with classes not in this dictionary are ignored.
CLASSES: {
  'movable_object.barrier':               'barrier',
  'vehicle.bicycle':                      'bicycle',
  'vehicle.bus.bendy':                    'bus',
  'vehicle.bus.rigid':                    'bus',
  'vehicle.car':                          'car',
  'vehicle.construction':                 'construction_vehicle',
  'vehicle.motorcycle':                   'motorcycle',
  'human.pedestrian.adult':               'pedestrian',
  'human.pedestrian.child':               'pedestrian',
  'human.pedestrian.construction_worker': 'pedestrian',
  'human.pedestrian.police_officer':      'pedestrian',
  'movable_object.trafficcone':           'traffic_cone',
  'vehicle.trailer':                      'trailer',
  'vehicle.truck':                        'truck',
}

## MISC ########################################################################
IMG_ID_LEN: 8                     # length of string image ID
PC_MIN_DIST: 1                    # Ignore points closer than this distance (m)
CONSOLE_LOG_LEVEL: "INFO"         # logging level for console
FILE_LOG_LEVEL: "WARNING"         # logging level for the log file
LOG_OUT_DIR: "../../output/logs"  # logging output directory
